modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/JustDoom/Axifier/issues"
license = "MIT"

[[mods]]
modId = "axifier"
version = "${version}"
displayName = "Axifier"
authors = "JustDoom"
description = '''
Collect their flesh without killing them! Cruelty free!
'''
logoFile = "logo-forge.png"

[[dependencies.axifier]]
modId = "neoforge"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.axifier]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "axifier-common.mixins.json"